# Generated by Django 4.1.6 on 2024-03-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cognom', models.CharField(max_length=50)),
                ('correu', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
                ('moduils', models.CharField(max_length=50)),
            ],
        ),
    ]
